services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public:ro
      - ./public/config.js:/app/public/config.js:ro
    environment:
      - NODE_ENV=production
